# Generated by Django 3.2.9 on 2022-01-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_route',
            name='is_on',
            field=models.BooleanField(default=True),
        ),
    ]
